version: '{branch}-{build}'
build: off
cache:
  - '%LOCALAPPDATA%\pip\Cache'
environment:
  matrix:
    - TOXENV: 'py311,report,codecov'
      PYTHON_HOME: C:\Python311-x64
      PYTHON_VERSION: '3.11'
      PYTHON_ARCH: '64'
init:
  - ps: echo $env:TOXENV
  - ps: ls C:\Python*
install:
  - '%PYTHON_HOME%\python -m pip install --upgrade pip tox'
  - '%PYTHON_HOME%\Scripts\tox --version'
test_script:
  - '%PYTHON_HOME%\Scripts\tox'

on_failure:
  - ps: dir "env:"
  - ps: get-content .tox\*\log\*
artifacts:
  - path: dist\*
